---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  call-workflow:
    uses: bitwarden/gh-actions/.github/workflows/workflow-linter.yml@70a5041f1f30dce0f303ec58e67f69dbfbf0807d
