---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**

permissions:
  contents: read

jobs:
  call-workflow:
    name: Call Workflow Linter
    uses: bitwarden/gh-actions/.github/workflows/workflow-linter.yml@abd4b8f01f8b34457a6ab35bd253768f4045231a
