---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  call-workflow:
    uses: bitwarden/gh-actions/.github/workflows/workflow-linter.yml@1fc74dd1f1d658ff25f25bed79bb7993f0024d87
