---
name: Workflow Linter

on:
  pull_request:
    paths:
      - .github/workflows/**

jobs:
  call-workflow:
    uses: bitwarden/gh-actions/.github/workflows/workflow-linter.yml@2a3ca6199a0724e0900da8283de906409a2abd4e
